AWSTemplateFormatVersion: '2010-09-09'
Description: Creates a CMK in KMS and grants access to other accounts

Resources:
  SampleBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 'sample-bucket-cross-account'
    DeletionPolicy: Delete

Outputs:
  SampleBucket:
    Value: !Ref SampleBucket
